-- Reference links for a content idea: 2-3 real links from different
-- sources — a real YouTube/Reddit URL for each signal that inspired the
-- idea (extracted from the signal itself, never generated by the AI, since
-- LLMs reliably hallucinate URLs), plus an Instagram hashtag-explore URL
-- (there's no Instagram API in this stack to fetch a real specific post,
-- so a hashtag-explore page — always valid, always shows genuinely
-- relevant real posts — stands in for one).

alter table content_ideas
  add column reference_links jsonb default '[]';
